name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
  dependencies: # change this
    required: true
    description: 'json string of dependencies'
runs:
  using: 'node12'
  main: 'dist/index.js'
