name: 'dependent jobs result check'
description: 'Checks if dependent jobs result matches provided statuses'
branding:
  icon: 'bell'
  color: 'green'
author: 'Layton Whiteley'
inputs:
  statuses:
    required: true
    description: 'comma seperated list of statuses to check'
  dependencies:
    required: true
    description: 'json string of dependencies'
outputs:
  statuses: 
    description: 'statuses found for jobs that match provided statuses'
  jobs: 
    description: 'comma list of jobs that included the provided statuses'
  found: 
    description: 'boolean of whether the provided statuses were found'
runs:
  using: 'node20'
  main: 'dist/index.js'
